import { getCurrentModel, saveCandidate } from '@/lib/learning/store'
import type { ProposedChange } from './policy'

export type ApplyResult = { current: any; candidate: any }

export async function applyProposedChange(proposed: ProposedChange): Promise<ApplyResult> {
  const cur = await getCurrentModel()
  const nextVersion = Math.max(proposed.versionTo, cur.version + 1)
  const candidate = {
    ...cur,
    version: nextVersion,
    parentVersion: cur.version,
    threshold: proposed.newThreshold,
    weights: { ...cur.weights, ...proposed.newWeights },
    calibrationBins: proposed.newCalibrationBins,
    notes: `${new Date().toISOString()} — candidate generated by adaptation policy (${proposed.severity})\nReason: ${proposed.reason}`,
    metricsAtBuild: proposed.expected
  }
  await saveCandidate(candidate)
  return { current: cur, candidate }
}


