import type { CalibrationVideo } from './calibration-scorer';
import { NICHE_REGISTRY } from '@/lib/prediction/system-registry';

// ─── Full Video Pool ─────────────────────────────────────────────────────────
// 160 videos — exactly 8 per niche × 20 niches. Each tagged on all 6 dimensions.
// All videos are niche-specific. No cross-niche mixing during calibration.

const VIDEO_POOL: CalibrationVideo[] = [
  // ── FITNESS (8 videos) ───────────────────────────────────────────────────
  {
    id: 'fit-01',
    title: 'I lost 30 lbs in 90 days without a gym membership',
    creator: '@coach_mikefitness',
    niche_tags: ['fitness', 'weight-loss'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'fitness',
      editing_style: 'before-after',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#4CAF50',
    views: 2_400_000,
    likes: 310_000,
    performance_tier: 'average',
  },
  {
    id: 'fit-02',
    title: 'Stop doing crunches. Here\'s what actually burns belly fat',
    creator: '@drfitscience',
    niche_tags: ['fitness', 'nutrition'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'listicle',
      niche_signal: 'fitness',
      editing_style: 'fast-cuts',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#FF5722',
    views: 5_100_000,
    likes: 620_000,
    performance_tier: 'high',
  },
  {
    id: 'fit-03',
    title: 'My client ate pizza every day and still got abs',
    creator: '@flexiblefitjess',
    niche_tags: ['fitness', 'nutrition'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'funny',
      content_format: 'story',
      niche_signal: 'fitness',
      editing_style: 'vlog-style',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#E91E63',
    views: 1_800_000,
    likes: 245_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'fit-04',
    title: '5 exercises you can do at your desk in 2 minutes',
    creator: '@officefitpro',
    niche_tags: ['fitness', 'wellness'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'casual',
      content_format: 'tutorial',
      niche_signal: 'fitness',
      editing_style: 'demo',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#2196F3',
    views: 890_000,
    likes: 112_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'fit-05',
    title: 'I trained like The Rock for 30 days. Here\'s what happened',
    creator: '@challengebro',
    niche_tags: ['fitness', 'lifestyle'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'vlog',
      niche_signal: 'fitness',
      editing_style: 'cinematic',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#9C27B0',
    views: 3_200_000,
    likes: 410_000,
    performance_tier: 'average',
  },
  {
    id: 'fit-06',
    title: 'The stretching routine that fixed my chronic back pain',
    creator: '@mobilityfix_dr',
    niche_tags: ['fitness', 'health'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'casual',
      content_format: 'explainer',
      niche_signal: 'fitness',
      editing_style: 'talking-head',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#00BCD4',
    views: 2_100_000,
    likes: 275_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'fit-07',
    title: 'Why your protein shake is sabotaging your gains',
    creator: '@gainscience_ry',
    niche_tags: ['fitness', 'nutrition'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'fitness',
      editing_style: 'split-screen',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#FF7043',
    views: 3_800_000,
    likes: 490_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'fit-08',
    title: 'Full body home workout — no equipment, 20 minutes',
    creator: '@homegym_queen',
    niche_tags: ['fitness', 'wellness'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'motivational',
      content_format: 'tutorial',
      niche_signal: 'fitness',
      editing_style: 'b-roll-heavy',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#7E57C2',
    views: 4_200_000,
    likes: 540_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── BUSINESS (8 videos) ──────────────────────────────────────────────────
  {
    id: 'biz-01',
    title: 'I made $10K/month at 22 with no degree. Here\'s the exact playbook',
    creator: '@hustlehub_alex',
    niche_tags: ['business', 'side-hustle'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'business',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FF9800',
    views: 4_500_000,
    likes: 520_000,
    performance_tier: 'high',
  },
  {
    id: 'biz-02',
    title: 'The 3 businesses you can start today with $0',
    creator: '@zerotofounder',
    niche_tags: ['business', 'entrepreneurship'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'authority',
      content_format: 'listicle',
      niche_signal: 'business',
      editing_style: 'fast-cuts',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#3F51B5',
    views: 6_200_000,
    likes: 780_000,
    performance_tier: 'high',
  },
  {
    id: 'biz-03',
    title: 'My boss fired me so I built an app that replaced him',
    creator: '@revengefounder',
    niche_tags: ['business', 'tech'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'funny',
      content_format: 'story',
      niche_signal: 'business',
      editing_style: 'meme-edit',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#F44336',
    views: 3_800_000,
    likes: 490_000,
    performance_tier: 'average',
  },
  {
    id: 'biz-04',
    title: 'You\'re not getting clients because your DMs look like this',
    creator: '@closercarla',
    niche_tags: ['business', 'sales'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'business',
      editing_style: 'split-screen',
      audience_pain: 'no-leads',
    },
    thumbnail_color: '#795548',
    views: 2_100_000,
    likes: 295_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'biz-05',
    title: 'I automated my entire business in one weekend using AI',
    creator: '@aiautomateguy',
    niche_tags: ['business', 'tech'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'casual',
      content_format: 'tutorial',
      niche_signal: 'business',
      editing_style: 'screen-record',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#009688',
    views: 1_500_000,
    likes: 198_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'biz-06',
    title: 'I landed my first $50K client using one cold email template',
    creator: '@coldemail_pro',
    niche_tags: ['business', 'sales'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'business',
      editing_style: 'cinematic',
      audience_pain: 'no-leads',
    },
    thumbnail_color: '#EF6C00',
    views: 3_300_000,
    likes: 425_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'biz-07',
    title: 'Why 90% of startups fail (and the 3 things survivors do)',
    creator: '@startupautopsy',
    niche_tags: ['business', 'entrepreneurship'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'casual',
      content_format: 'explainer',
      niche_signal: 'business',
      editing_style: 'whiteboard',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#5C6BC0',
    views: 2_700_000,
    likes: 350_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'biz-08',
    title: 'From garage to $1M ARR: the full breakdown',
    creator: '@founderstory_kai',
    niche_tags: ['business', 'side-hustle'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'vlog',
      niche_signal: 'business',
      editing_style: 'b-roll-heavy',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#26A69A',
    views: 4_900_000,
    likes: 630_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── BEAUTY (8 videos) ────────────────────────────────────────────────────
  {
    id: 'bty-01',
    title: 'Dermatologists are lying to you about sunscreen',
    creator: '@skinbyria',
    niche_tags: ['beauty', 'skincare'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'beauty',
      editing_style: 'fast-cuts',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#E040FB',
    views: 7_300_000,
    likes: 920_000,
    performance_tier: 'high',
  },
  {
    id: 'bty-02',
    title: '3-minute morning routine that changed my skin forever',
    creator: '@glowup_nina',
    niche_tags: ['beauty', 'skincare'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'tutorial',
      niche_signal: 'beauty',
      editing_style: 'asmr',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#FF80AB',
    views: 2_900_000,
    likes: 375_000,
    performance_tier: 'average',
  },
  {
    id: 'bty-03',
    title: 'I tried every viral foundation so you don\'t have to',
    creator: '@honestmakeup_sam',
    niche_tags: ['beauty', 'makeup'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'funny',
      content_format: 'comparison',
      niche_signal: 'beauty',
      editing_style: 'before-after',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#CE93D8',
    views: 4_100_000,
    likes: 530_000,
    performance_tier: 'average',
  },
  {
    id: 'bty-04',
    title: 'The $5 product that replaced my entire skincare shelf',
    creator: '@budgetbeautyqueen',
    niche_tags: ['beauty', 'skincare'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'casual',
      content_format: 'review',
      niche_signal: 'beauty',
      editing_style: 'vlog-style',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FFAB91',
    views: 1_600_000,
    likes: 210_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'bty-05',
    title: 'Glass skin in 7 days — the Korean routine that actually works',
    creator: '@kbeauty_claire',
    niche_tags: ['beauty', 'skincare'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'beauty',
      editing_style: 'cinematic',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#F48FB1',
    views: 5_200_000,
    likes: 670_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'bty-06',
    title: '5 makeup mistakes that age you (and what to do instead)',
    creator: '@agelessglam_dr',
    niche_tags: ['beauty', 'makeup'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'authority',
      content_format: 'listicle',
      niche_signal: 'beauty',
      editing_style: 'split-screen',
      audience_pain: 'body-image',
    },
    thumbnail_color: '#BA68C8',
    views: 3_600_000,
    likes: 465_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'bty-07',
    title: 'I spent $2000 on skincare so you don\'t have to — honest reviews',
    creator: '@skinsplurge_tina',
    niche_tags: ['beauty', 'skincare'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'casual',
      content_format: 'review',
      niche_signal: 'beauty',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#E1BEE7',
    views: 2_300_000,
    likes: 300_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'bty-08',
    title: 'The ingredient your dermatologist wishes you\'d stop using',
    creator: '@dermatalk_dr',
    niche_tags: ['beauty', 'health'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'funny',
      content_format: 'story',
      niche_signal: 'beauty',
      editing_style: 'demo',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#F06292',
    views: 4_800_000,
    likes: 615_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── EDUCATION (8 videos) ─────────────────────────────────────────────────
  {
    id: 'edu-01',
    title: 'Your teacher was wrong about how memory works',
    creator: '@learnlabmax',
    niche_tags: ['education', 'productivity'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'education',
      editing_style: 'whiteboard',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#42A5F5',
    views: 3_400_000,
    likes: 440_000,
    performance_tier: 'high',
  },
  {
    id: 'edu-02',
    title: 'I read 100 books in 2025. These 3 changed everything',
    creator: '@bookstack_jo',
    niche_tags: ['education', 'self-improvement'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'listicle',
      niche_signal: 'education',
      editing_style: 'b-roll-heavy',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#66BB6A',
    views: 2_700_000,
    likes: 350_000,
    performance_tier: 'average',
  },
  {
    id: 'edu-03',
    title: 'Study hack: I passed the bar exam studying 2 hours a day',
    creator: '@lazylearner_dev',
    niche_tags: ['education', 'career'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'casual',
      content_format: 'story',
      niche_signal: 'education',
      editing_style: 'talking-head',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#FFCA28',
    views: 1_900_000,
    likes: 265_000,
    performance_tier: 'underperformer',
  },
  {
    id: 'edu-04',
    title: 'The Feynman Technique explained in 60 seconds',
    creator: '@sciencesimple_zoe',
    niche_tags: ['education', 'productivity'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'casual',
      content_format: 'tutorial',
      niche_signal: 'education',
      editing_style: 'fast-cuts',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#29B6F6',
    views: 4_100_000,
    likes: 530_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'edu-05',
    title: 'Why straight-A students often fail in the real world',
    creator: '@realworld_prof',
    niche_tags: ['education', 'career'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'education',
      editing_style: 'cinematic',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#81C784',
    views: 5_600_000,
    likes: 720_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'edu-06',
    title: 'I learned calculus in 30 days using only YouTube',
    creator: '@selfteach_mark',
    niche_tags: ['education', 'self-improvement'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'education',
      editing_style: 'vlog-style',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#FFD54F',
    views: 3_200_000,
    likes: 415_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'edu-07',
    title: '3 note-taking methods ranked (I tested all of them)',
    creator: '@notesmaster_ali',
    niche_tags: ['education', 'productivity'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'funny',
      content_format: 'comparison',
      niche_signal: 'education',
      editing_style: 'split-screen',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#4FC3F7',
    views: 2_800_000,
    likes: 360_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'edu-08',
    title: 'How spaced repetition tricked my brain into remembering everything',
    creator: '@memoryhack_dr',
    niche_tags: ['education', 'psychology'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'education',
      editing_style: 'demo',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#AED581',
    views: 1_700_000,
    likes: 220_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },

  // ── REAL ESTATE (8 videos) ───────────────────────────────────────────────
  {
    id: 're-01',
    title: 'How I bought my first rental property at 24 with no savings',
    creator: '@propertypulse_jay',
    niche_tags: ['real-estate', 'investing'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'real-estate',
      editing_style: 'cinematic',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#8D6E63',
    views: 2_800_000,
    likes: 360_000,
    performance_tier: 'average',
  },
  {
    id: 're-02',
    title: 'Never buy a house with these 3 red flags',
    creator: '@realtalkrenee',
    niche_tags: ['real-estate', 'home-buying'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'authority',
      content_format: 'listicle',
      niche_signal: 'real-estate',
      editing_style: 'fast-cuts',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#546E7A',
    views: 3_500_000,
    likes: 450_000,
    performance_tier: 'average',
  },
  {
    id: 're-03',
    title: 'Your realtor doesn\'t want you to know this negotiation trick',
    creator: '@insiderdealsmike',
    niche_tags: ['real-estate', 'investing'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'funny',
      content_format: 'explainer',
      niche_signal: 'real-estate',
      editing_style: 'meme-edit',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#D4E157',
    views: 4_600_000,
    likes: 590_000,
    performance_tier: 'high',
  },
  {
    id: 're-04',
    title: 'House hacking 101: live for free while building wealth',
    creator: '@househack_maya',
    niche_tags: ['real-estate', 'personal-finance'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'casual',
      content_format: 'tutorial',
      niche_signal: 'real-estate',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#A1887F',
    views: 2_200_000,
    likes: 285_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 're-05',
    title: 'I flipped a house in 60 days — full cost breakdown',
    creator: '@flipper_dan',
    niche_tags: ['real-estate', 'diy'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'real-estate',
      editing_style: 'before-after',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#78909C',
    views: 5_100_000,
    likes: 655_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 're-06',
    title: 'Why renting is smarter than buying (controversial take)',
    creator: '@rentvsown_prof',
    niche_tags: ['real-estate', 'personal-finance'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'real-estate',
      editing_style: 'whiteboard',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#B0BEC5',
    views: 3_800_000,
    likes: 490_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 're-07',
    title: '5 things I wish I knew before buying my first home',
    creator: '@firsthome_alex',
    niche_tags: ['real-estate', 'home-buying'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'casual',
      content_format: 'vlog',
      niche_signal: 'real-estate',
      editing_style: 'vlog-style',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#BCAAA4',
    views: 1_600_000,
    likes: 210_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 're-08',
    title: 'How to spot a money pit before you sign (inspector secrets)',
    creator: '@inspectorinsider',
    niche_tags: ['real-estate', 'home-buying'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'funny',
      content_format: 'story',
      niche_signal: 'real-estate',
      editing_style: 'demo',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#90A4AE',
    views: 4_200_000,
    likes: 540_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── SIDE HUSTLES (8 videos) ──────────────────────────────────────────────
  {
    id: 'sh-01',
    title: 'I made $3K last month selling digital planners on Etsy',
    creator: '@sideincome_sara',
    niche_tags: ['side-hustles', 'business'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'side-hustles',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FF6F00',
    views: 3_100_000,
    likes: 405_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'sh-02',
    title: '5 side hustles you can start tonight with just your phone',
    creator: '@phonehustle_dan',
    niche_tags: ['side-hustles', 'tech'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'casual',
      content_format: 'listicle',
      niche_signal: 'side-hustles',
      editing_style: 'fast-cuts',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FFA726',
    views: 5_400_000,
    likes: 680_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'sh-03',
    title: 'Stop wasting time on surveys. Here\'s what actually pays',
    creator: '@realhustle_kim',
    niche_tags: ['side-hustles', 'personal-finance'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'side-hustles',
      editing_style: 'split-screen',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#E65100',
    views: 2_800_000,
    likes: 360_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'sh-04',
    title: 'I quit my 9-5 after this side hustle hit $8K/month',
    creator: '@quitthegrind_ty',
    niche_tags: ['side-hustles', 'career'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'vlog',
      niche_signal: 'side-hustles',
      editing_style: 'cinematic',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#BF360C',
    views: 4_200_000,
    likes: 540_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'sh-05',
    title: 'Print on demand in 2026: still worth it? Full breakdown',
    creator: '@podreview_amy',
    niche_tags: ['side-hustles', 'business'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'casual',
      content_format: 'explainer',
      niche_signal: 'side-hustles',
      editing_style: 'screen-record',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#FFB74D',
    views: 2_300_000,
    likes: 300_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'sh-06',
    title: 'How I turned a $50 camera into a $5K/month freelance gig',
    creator: '@freelancegrind_jo',
    niche_tags: ['side-hustles', 'career'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'side-hustles',
      editing_style: 'before-after',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FF8F00',
    views: 3_600_000,
    likes: 465_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'sh-07',
    title: 'The one skill that makes every side hustle easier',
    creator: '@skillstack_ray',
    niche_tags: ['side-hustles', 'self-improvement'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'authority',
      content_format: 'tutorial',
      niche_signal: 'side-hustles',
      editing_style: 'whiteboard',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#F57C00',
    views: 1_900_000,
    likes: 245_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'sh-08',
    title: 'I tested 10 AI side hustles. Only 2 actually made money',
    creator: '@aiside_test',
    niche_tags: ['side-hustles', 'tech'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'funny',
      content_format: 'review',
      niche_signal: 'side-hustles',
      editing_style: 'demo',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#EF6C00',
    views: 6_100_000,
    likes: 785_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── PERSONAL FINANCE (8 videos) ──────────────────────────────────────────
  {
    id: 'pf-01',
    title: 'I saved $20K in 12 months on a $45K salary. Here\'s how',
    creator: '@budgetboss_lex',
    niche_tags: ['personal-finance', 'self-improvement'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'personal-finance',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#1B5E20',
    views: 3_600_000,
    likes: 470_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'pf-02',
    title: 'The 50/30/20 rule is outdated. Try this instead',
    creator: '@moneynerds_jo',
    niche_tags: ['personal-finance', 'education'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'personal-finance',
      editing_style: 'whiteboard',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#2E7D32',
    views: 2_400_000,
    likes: 310_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'pf-03',
    title: '3 investing mistakes I made in my 20s (don\'t repeat them)',
    creator: '@earlyretire_mo',
    niche_tags: ['personal-finance', 'business'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'casual',
      content_format: 'listicle',
      niche_signal: 'personal-finance',
      editing_style: 'b-roll-heavy',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#388E3C',
    views: 1_900_000,
    likes: 250_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'pf-04',
    title: 'Index funds vs individual stocks — the math nobody shows you',
    creator: '@mathofmoney_dr',
    niche_tags: ['personal-finance', 'education'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'personal-finance',
      editing_style: 'split-screen',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#43A047',
    views: 4_200_000,
    likes: 540_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'pf-05',
    title: 'How I paid off $80K in student loans in 3 years',
    creator: '@debtfree_nina',
    niche_tags: ['personal-finance', 'career'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'personal-finance',
      editing_style: 'cinematic',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#4CAF50',
    views: 5_800_000,
    likes: 745_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'pf-06',
    title: 'The credit card hack banks don\'t advertise',
    creator: '@creditwise_tom',
    niche_tags: ['personal-finance', 'side-hustles'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'funny',
      content_format: 'tutorial',
      niche_signal: 'personal-finance',
      editing_style: 'fast-cuts',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#66BB6A',
    views: 3_100_000,
    likes: 400_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'pf-07',
    title: 'Emergency fund or invest? The answer might surprise you',
    creator: '@moneydilemma_ray',
    niche_tags: ['personal-finance', 'self-improvement'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'casual',
      content_format: 'story',
      niche_signal: 'personal-finance',
      editing_style: 'vlog-style',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#81C784',
    views: 2_600_000,
    likes: 335_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'pf-08',
    title: 'Your savings account is losing you money — here\'s why',
    creator: '@inflationwatch_sam',
    niche_tags: ['personal-finance', 'education'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'personal-finance',
      editing_style: 'demo',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#A5D6A7',
    views: 4_500_000,
    likes: 580_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── FOOD/NUTRITION (8 videos) ────────────────────────────────────────────
  {
    id: 'fn-01',
    title: 'This "healthy" breakfast is worse than a donut',
    creator: '@truthfuel_amy',
    niche_tags: ['food-nutrition', 'health'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'food-nutrition',
      editing_style: 'split-screen',
      audience_pain: 'health-anxiety',
    },
    thumbnail_color: '#F57F17',
    views: 4_800_000,
    likes: 610_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'fn-02',
    title: 'What 2000 calories actually looks like (you\'ll be shocked)',
    creator: '@caloriecheck_rj',
    niche_tags: ['food-nutrition', 'fitness'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'casual',
      content_format: 'explainer',
      niche_signal: 'food-nutrition',
      editing_style: 'demo',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#F9A825',
    views: 3_200_000,
    likes: 415_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'fn-03',
    title: 'A nutritionist rates my full day of eating',
    creator: '@ratemyplate_liv',
    niche_tags: ['food-nutrition', 'cooking'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'funny',
      content_format: 'review',
      niche_signal: 'food-nutrition',
      editing_style: 'vlog-style',
      audience_pain: 'meal-fatigue',
    },
    thumbnail_color: '#FDD835',
    views: 2_100_000,
    likes: 275_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'fn-04',
    title: 'Seed oils: actually toxic or just fear mongering?',
    creator: '@foodfacts_dr',
    niche_tags: ['food-nutrition', 'health'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'food-nutrition',
      editing_style: 'whiteboard',
      audience_pain: 'health-anxiety',
    },
    thumbnail_color: '#FFEE58',
    views: 5_600_000,
    likes: 720_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'fn-05',
    title: '5 superfoods that are actually just marketing',
    creator: '@nutriscience_ben',
    niche_tags: ['food-nutrition', 'education'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'casual',
      content_format: 'listicle',
      niche_signal: 'food-nutrition',
      editing_style: 'fast-cuts',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#FFF176',
    views: 3_900_000,
    likes: 500_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'fn-06',
    title: 'I ate only whole foods for 30 days — blood work results',
    creator: '@cleaneat_challenge',
    niche_tags: ['food-nutrition', 'fitness'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'food-nutrition',
      editing_style: 'before-after',
      audience_pain: 'health-anxiety',
    },
    thumbnail_color: '#FBC02D',
    views: 4_400_000,
    likes: 565_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'fn-07',
    title: 'The protein myth that\'s costing you gains and money',
    creator: '@proteintruth_rj',
    niche_tags: ['food-nutrition', 'fitness'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'funny',
      content_format: 'story',
      niche_signal: 'food-nutrition',
      editing_style: 'talking-head',
      audience_pain: 'meal-fatigue',
    },
    thumbnail_color: '#F9A825',
    views: 2_700_000,
    likes: 350_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'fn-08',
    title: 'Grocery store tricks that make you spend more',
    creator: '@smartshopper_lu',
    niche_tags: ['food-nutrition', 'personal-finance'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'tutorial',
      niche_signal: 'food-nutrition',
      editing_style: 'cinematic',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#FFD600',
    views: 3_300_000,
    likes: 425_000,
    performance_tier: 'average',
    placeholder: true,
  },

  // ── SELF-IMPROVEMENT (8 videos) ──────────────────────────────────────────
  {
    id: 'si-01',
    title: 'I woke up at 5am for 365 days. Here\'s what changed',
    creator: '@habitforge_will',
    niche_tags: ['self-improvement', 'fitness'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'self-improvement',
      editing_style: 'cinematic',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#6A1B9A',
    views: 4_500_000,
    likes: 580_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'si-02',
    title: 'The 2-minute rule that fixed my procrastination',
    creator: '@mindshift_tara',
    niche_tags: ['self-improvement', 'education'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'self-improvement',
      editing_style: 'whiteboard',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#7B1FA2',
    views: 3_800_000,
    likes: 490_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'si-03',
    title: 'Stop reading self-help books. Do this instead',
    creator: '@contrarian_dev',
    niche_tags: ['self-improvement', 'psychology'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'casual',
      content_format: 'story',
      niche_signal: 'self-improvement',
      editing_style: 'talking-head',
      audience_pain: 'information-overload',
    },
    thumbnail_color: '#8E24AA',
    views: 2_600_000,
    likes: 335_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'si-04',
    title: 'My therapist taught me this journaling trick and it changed everything',
    creator: '@innergrowth_paz',
    niche_tags: ['self-improvement', 'psychology'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'tutorial',
      niche_signal: 'self-improvement',
      editing_style: 'b-roll-heavy',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#AB47BC',
    views: 1_700_000,
    likes: 220_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'si-05',
    title: '5 habits that made me unrecognizable in 6 months',
    creator: '@levelup_co',
    niche_tags: ['self-improvement', 'fitness'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'motivational',
      content_format: 'listicle',
      niche_signal: 'self-improvement',
      editing_style: 'fast-cuts',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#9C27B0',
    views: 5_200_000,
    likes: 670_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'si-06',
    title: 'Why discipline is overrated (build systems instead)',
    creator: '@systems_sam',
    niche_tags: ['self-improvement', 'business'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'casual',
      content_format: 'comparison',
      niche_signal: 'self-improvement',
      editing_style: 'split-screen',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#CE93D8',
    views: 3_400_000,
    likes: 440_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'si-07',
    title: 'I deleted social media for 90 days — here\'s the truth',
    creator: '@detox_diaries',
    niche_tags: ['self-improvement', 'psychology'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'funny',
      content_format: 'vlog',
      niche_signal: 'self-improvement',
      editing_style: 'vlog-style',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#BA68C8',
    views: 4_100_000,
    likes: 530_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'si-08',
    title: 'The morning routine science says actually works',
    creator: '@morningscience_dr',
    niche_tags: ['self-improvement', 'health'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'authority',
      content_format: 'review',
      niche_signal: 'self-improvement',
      editing_style: 'demo',
      audience_pain: 'time-scarcity',
    },
    thumbnail_color: '#E1BEE7',
    views: 2_900_000,
    likes: 375_000,
    performance_tier: 'average',
    placeholder: true,
  },

  // ── DATING (8 videos) ────────────────────────────────────────────────────
  {
    id: 'dat-01',
    title: 'The texting mistake that kills attraction every time',
    creator: '@datingdecoded_max',
    niche_tags: ['dating', 'psychology'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'dating',
      editing_style: 'fast-cuts',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#C62828',
    views: 5_200_000,
    likes: 670_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'dat-02',
    title: 'I went on 30 first dates in 30 days. Here\'s what I learned',
    creator: '@datelab_nina',
    niche_tags: ['dating', 'self-improvement'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'funny',
      content_format: 'vlog',
      niche_signal: 'dating',
      editing_style: 'vlog-style',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#D32F2F',
    views: 3_900_000,
    likes: 505_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'dat-03',
    title: 'Body language signs they\'re into you (backed by science)',
    creator: '@socialcues_raj',
    niche_tags: ['dating', 'psychology'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'casual',
      content_format: 'listicle',
      niche_signal: 'dating',
      editing_style: 'demo',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#EF5350',
    views: 2_300_000,
    likes: 300_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'dat-04',
    title: 'Red flags vs green flags: dating edition',
    creator: '@flagcheck_zoe',
    niche_tags: ['dating', 'psychology'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'dating',
      editing_style: 'split-screen',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#E53935',
    views: 4_600_000,
    likes: 590_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'dat-05',
    title: 'How I fixed my dating profile and tripled my matches',
    creator: '@profilefix_jay',
    niche_tags: ['dating', 'self-improvement'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'dating',
      editing_style: 'before-after',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#F44336',
    views: 3_100_000,
    likes: 400_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'dat-06',
    title: 'Dating coaches are scamming you — here\'s free advice that works',
    creator: '@honestdating_lu',
    niche_tags: ['dating', 'self-improvement'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'casual',
      content_format: 'story',
      niche_signal: 'dating',
      editing_style: 'talking-head',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#E57373',
    views: 5_800_000,
    likes: 745_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'dat-07',
    title: 'First date ideas that actually lead to second dates',
    creator: '@dateideas_mia',
    niche_tags: ['dating', 'lifestyle'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'funny',
      content_format: 'tutorial',
      niche_signal: 'dating',
      editing_style: 'cinematic',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#EF9A9A',
    views: 2_700_000,
    likes: 350_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'dat-08',
    title: 'Why you keep attracting the wrong people (psychology explains)',
    creator: '@attractionscience',
    niche_tags: ['dating', 'psychology'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'motivational',
      content_format: 'explainer',
      niche_signal: 'dating',
      editing_style: 'whiteboard',
      audience_pain: 'loneliness',
    },
    thumbnail_color: '#FFCDD2',
    views: 4_300_000,
    likes: 555_000,
    performance_tier: 'average',
    placeholder: true,
  },

  // ── CAREER (8 videos) ────────────────────────────────────────────────────
  {
    id: 'car-01',
    title: 'I doubled my salary in 18 months using this LinkedIn strategy',
    creator: '@careerboost_lena',
    niche_tags: ['career', 'business'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'motivational',
      content_format: 'story',
      niche_signal: 'career',
      editing_style: 'talking-head',
      audience_pain: 'career-stagnation',
    },
    thumbnail_color: '#0D47A1',
    views: 3_400_000,
    likes: 440_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'car-02',
    title: 'Your resume is getting rejected by bots. Fix it in 5 minutes',
    creator: '@resumefix_omar',
    niche_tags: ['career', 'tech'],
    attribute_tags: {
      hook_style: 'myth_bust',
      tone: 'authority',
      content_format: 'tutorial',
      niche_signal: 'career',
      editing_style: 'screen-record',
      audience_pain: 'career-stagnation',
    },
    thumbnail_color: '#1565C0',
    views: 4_700_000,
    likes: 600_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'car-03',
    title: 'The salary negotiation script that got me a 40% raise',
    creator: '@negotiateup_ash',
    niche_tags: ['career', 'personal-finance'],
    attribute_tags: {
      hook_style: 'personal_story',
      tone: 'casual',
      content_format: 'explainer',
      niche_signal: 'career',
      editing_style: 'fast-cuts',
      audience_pain: 'money-anxiety',
    },
    thumbnail_color: '#1976D2',
    views: 2_800_000,
    likes: 365_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'car-04',
    title: 'How to answer "Tell me about yourself" (with exact scripts)',
    creator: '@interview_ace',
    niche_tags: ['career', 'self-improvement'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'casual',
      content_format: 'tutorial',
      niche_signal: 'career',
      editing_style: 'demo',
      audience_pain: 'career-stagnation',
    },
    thumbnail_color: '#1E88E5',
    views: 5_300_000,
    likes: 680_000,
    performance_tier: 'high',
    placeholder: true,
  },
  {
    id: 'car-05',
    title: 'I got promoted 3 times in 2 years — here\'s the playbook',
    creator: '@climbfast_ria',
    niche_tags: ['career', 'business'],
    attribute_tags: {
      hook_style: 'question',
      tone: 'motivational',
      content_format: 'transformation',
      niche_signal: 'career',
      editing_style: 'cinematic',
      audience_pain: 'career-stagnation',
    },
    thumbnail_color: '#2196F3',
    views: 3_900_000,
    likes: 500_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'car-06',
    title: 'Quiet quitting vs setting boundaries — know the difference',
    creator: '@workbalance_kai',
    niche_tags: ['career', 'psychology'],
    attribute_tags: {
      hook_style: 'contrarian',
      tone: 'authority',
      content_format: 'comparison',
      niche_signal: 'career',
      editing_style: 'split-screen',
      audience_pain: 'burnout',
    },
    thumbnail_color: '#42A5F5',
    views: 4_100_000,
    likes: 530_000,
    performance_tier: 'average',
    placeholder: true,
  },
  {
    id: 'car-07',
    title: 'The networking hack introverts swear by',
    creator: '@introvertwin_sam',
    niche_tags: ['career', 'self-improvement'],
    attribute_tags: {
      hook_style: 'authority',
      tone: 'funny',
      content_format: 'listicle',
      niche_signal: 'career',
      editing_style: 'vlog-style',
      audience_pain: 'imposter-syndrome',
    },
    thumbnail_color: '#64B5F6',
    views: 2_200_000,
    likes: 285_000,
    performance_tier: 'underperformer',
    placeholder: true,
  },
  {
    id: 'car-08',
    title: 'Skills that will be obsolete by 2028 (start learning these instead)',
    creator: '@futureproof_dev',
    niche_tags: ['career', 'tech'],
    attribute_tags: {
      hook_style: 'list_preview',
      tone: 'authority',
      content_format: 'explainer',
      niche_signal: 'career',
      editing_style: 'whiteboard',
      audience_pain: 'career-stagnation',
    },
    thumbnail_color: '#90CAF9',
    views: 6_200_000,
    likes: 795_000,
    performance_tier: 'high',
    placeholder: true,
  },

  // ── PARENTING (8 videos) ─────────────────────────────────────────────────
  {
    id: 'par-01',
    title: 'The one phrase that stops toddler tantrums instantly',
    creator: '@calmparent_jo',
    niche_tags: ['parenting', 'psychology'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'parenting', editing_style: 'talking-head', audience_pain: 'parenting-guilt' },
    thumbnail_color: '#00838F', views: 4_100_000, likes: 530_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'par-02',
    title: 'I stopped yelling at my kids for 30 days. Here\'s what happened',
    creator: '@gentledad_marcus',
    niche_tags: ['parenting', 'self-improvement'],
    attribute_tags: { hook_style: 'question', tone: 'motivational', content_format: 'transformation', niche_signal: 'parenting', editing_style: 'vlog-style', audience_pain: 'parenting-guilt' },
    thumbnail_color: '#0097A7', views: 3_300_000, likes: 425_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'par-03',
    title: 'Screen time rules that actually work (from a child psychologist)',
    creator: '@drscreen_laura',
    niche_tags: ['parenting', 'health'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'authority', content_format: 'explainer', niche_signal: 'parenting', editing_style: 'whiteboard', audience_pain: 'information-overload' },
    thumbnail_color: '#00ACC1', views: 2_500_000, likes: 320_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'par-04',
    title: 'What to say instead of "Good job" (it changes everything)',
    creator: '@positiveparent_dr',
    niche_tags: ['parenting', 'psychology'],
    attribute_tags: { hook_style: 'contrarian', tone: 'authority', content_format: 'comparison', niche_signal: 'parenting', editing_style: 'split-screen', audience_pain: 'parenting-guilt' },
    thumbnail_color: '#00BCD4', views: 5_400_000, likes: 695_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'par-05',
    title: '5 lunch ideas your picky eater will actually eat',
    creator: '@pickyfix_mama',
    niche_tags: ['parenting', 'cooking'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'listicle', niche_signal: 'parenting', editing_style: 'demo', audience_pain: 'meal-fatigue' },
    thumbnail_color: '#26C6DA', views: 2_900_000, likes: 375_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'par-06',
    title: 'My bedtime routine that gets 3 kids asleep by 7:30',
    creator: '@bedtimehero_kate',
    niche_tags: ['parenting', 'self-improvement'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'story', niche_signal: 'parenting', editing_style: 'cinematic', audience_pain: 'time-scarcity' },
    thumbnail_color: '#4DD0E1', views: 3_700_000, likes: 475_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'par-07',
    title: 'The toy rotation system that stopped the meltdowns',
    creator: '@organizedmom_lu',
    niche_tags: ['parenting', 'diy'],
    attribute_tags: { hook_style: 'authority', tone: 'funny', content_format: 'tutorial', niche_signal: 'parenting', editing_style: 'before-after', audience_pain: 'parenting-guilt' },
    thumbnail_color: '#80DEEA', views: 1_800_000, likes: 235_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'par-08',
    title: 'Things I stopped doing as a parent (and why life got better)',
    creator: '@imperfectdad_ray',
    niche_tags: ['parenting', 'psychology'],
    attribute_tags: { hook_style: 'personal_story', tone: 'casual', content_format: 'vlog', niche_signal: 'parenting', editing_style: 'b-roll-heavy', audience_pain: 'burnout' },
    thumbnail_color: '#B2EBF2', views: 4_500_000, likes: 580_000,
    performance_tier: 'high', placeholder: true,
  },

  // ── TECH (8 videos) ──────────────────────────────────────────────────────
  {
    id: 'tech-01',
    title: 'Don\'t buy the new iPhone until you see this comparison',
    creator: '@techtruth_kai',
    niche_tags: ['tech', 'business'],
    attribute_tags: { hook_style: 'contrarian', tone: 'authority', content_format: 'comparison', niche_signal: 'tech', editing_style: 'split-screen', audience_pain: 'decision-paralysis' },
    thumbnail_color: '#37474F', views: 5_600_000, likes: 720_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'tech-02',
    title: '7 free apps that replaced $500 of software for me',
    creator: '@freetech_ava',
    niche_tags: ['tech', 'side-hustles'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'listicle', niche_signal: 'tech', editing_style: 'screen-record', audience_pain: 'money-anxiety' },
    thumbnail_color: '#455A64', views: 4_300_000, likes: 555_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'tech-03',
    title: 'I built an app in 24 hours using AI. No coding needed',
    creator: '@nocodenoah',
    niche_tags: ['tech', 'education'],
    attribute_tags: { hook_style: 'question', tone: 'motivational', content_format: 'vlog', niche_signal: 'tech', editing_style: 'cinematic', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#546E7A', views: 3_100_000, likes: 400_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'tech-04',
    title: 'Your Wi-Fi is slow because of this one setting',
    creator: '@quickfix_tech',
    niche_tags: ['tech', 'diy'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'funny', content_format: 'tutorial', niche_signal: 'tech', editing_style: 'demo', audience_pain: 'decision-paralysis' },
    thumbnail_color: '#607D8B', views: 6_800_000, likes: 870_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'tech-05',
    title: 'The privacy settings you need to change RIGHT NOW',
    creator: '@privacyguard_dev',
    niche_tags: ['tech', 'education'],
    attribute_tags: { hook_style: 'authority', tone: 'authority', content_format: 'tutorial', niche_signal: 'tech', editing_style: 'fast-cuts', audience_pain: 'information-overload' },
    thumbnail_color: '#78909C', views: 3_800_000, likes: 490_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'tech-06',
    title: 'M4 MacBook vs gaming laptop: which one should you buy?',
    creator: '@laptopshowdown_zz',
    niche_tags: ['tech', 'business'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'comparison', niche_signal: 'tech', editing_style: 'b-roll-heavy', audience_pain: 'decision-paralysis' },
    thumbnail_color: '#90A4AE', views: 4_900_000, likes: 630_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'tech-07',
    title: 'I tried every AI assistant for a week — honest ranking',
    creator: '@airanker_tom',
    niche_tags: ['tech', 'self-improvement'],
    attribute_tags: { hook_style: 'question', tone: 'casual', content_format: 'review', niche_signal: 'tech', editing_style: 'talking-head', audience_pain: 'decision-paralysis' },
    thumbnail_color: '#B0BEC5', views: 5_200_000, likes: 670_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'tech-08',
    title: 'How to set up a home server for $50 (complete guide)',
    creator: '@homelab_hero',
    niche_tags: ['tech', 'diy'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'story', niche_signal: 'tech', editing_style: 'whiteboard', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#CFD8DC', views: 2_400_000, likes: 310_000,
    performance_tier: 'underperformer', placeholder: true,
  },

  // ── FASHION (8 videos) ───────────────────────────────────────────────────
  {
    id: 'fash-01',
    title: 'Build a capsule wardrobe with just 15 pieces',
    creator: '@minimalstyle_em',
    niche_tags: ['fashion', 'self-improvement'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'fashion', editing_style: 'b-roll-heavy', audience_pain: 'style-insecurity' },
    thumbnail_color: '#880E4F', views: 2_700_000, likes: 350_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'fash-02',
    title: 'Outfit mistakes that make you look 10 years older',
    creator: '@agelessstyle_ren',
    niche_tags: ['fashion', 'beauty'],
    attribute_tags: { hook_style: 'list_preview', tone: 'authority', content_format: 'comparison', niche_signal: 'fashion', editing_style: 'before-after', audience_pain: 'style-insecurity' },
    thumbnail_color: '#AD1457', views: 4_000_000, likes: 515_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'fash-03',
    title: 'I styled $30 thrift hauls to look like $300 outfits',
    creator: '@thriftglow_zee',
    niche_tags: ['fashion', 'side-hustles'],
    attribute_tags: { hook_style: 'question', tone: 'funny', content_format: 'transformation', niche_signal: 'fashion', editing_style: 'fast-cuts', audience_pain: 'money-anxiety' },
    thumbnail_color: '#C2185B', views: 3_500_000, likes: 450_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'fash-04',
    title: 'The color theory trick that makes any outfit pop',
    creator: '@colorstyle_dr',
    niche_tags: ['fashion', 'education'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'authority', content_format: 'explainer', niche_signal: 'fashion', editing_style: 'whiteboard', audience_pain: 'style-insecurity' },
    thumbnail_color: '#D81B60', views: 3_200_000, likes: 415_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'fash-05',
    title: 'Dressing for your body type is a myth — here\'s why',
    creator: '@bodyfree_jo',
    niche_tags: ['fashion', 'psychology'],
    attribute_tags: { hook_style: 'contrarian', tone: 'casual', content_format: 'story', niche_signal: 'fashion', editing_style: 'talking-head', audience_pain: 'body-image' },
    thumbnail_color: '#E91E63', views: 5_100_000, likes: 655_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'fash-06',
    title: 'Fall wardrobe essentials that work for every style',
    creator: '@seasonal_chic',
    niche_tags: ['fashion', 'beauty'],
    attribute_tags: { hook_style: 'list_preview', tone: 'motivational', content_format: 'listicle', niche_signal: 'fashion', editing_style: 'cinematic', audience_pain: 'style-insecurity' },
    thumbnail_color: '#EC407A', views: 2_400_000, likes: 310_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'fash-07',
    title: 'I wore the same 5 outfits for a month — nobody noticed',
    creator: '@uniform_project',
    niche_tags: ['fashion', 'self-improvement'],
    attribute_tags: { hook_style: 'question', tone: 'motivational', content_format: 'vlog', niche_signal: 'fashion', editing_style: 'vlog-style', audience_pain: 'time-scarcity' },
    thumbnail_color: '#F06292', views: 4_600_000, likes: 590_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'fash-08',
    title: 'How to find your personal style in 10 minutes',
    creator: '@stylequiz_lena',
    niche_tags: ['fashion', 'self-improvement'],
    attribute_tags: { hook_style: 'personal_story', tone: 'casual', content_format: 'tutorial', niche_signal: 'fashion', editing_style: 'demo', audience_pain: 'style-insecurity' },
    thumbnail_color: '#F48FB1', views: 1_900_000, likes: 245_000,
    performance_tier: 'underperformer', placeholder: true,
  },

  // ── HEALTH (8 videos) ────────────────────────────────────────────────────
  {
    id: 'hlth-01',
    title: 'Your doctor won\'t tell you this about inflammation',
    creator: '@holistichealth_dr',
    niche_tags: ['health', 'food-nutrition'],
    attribute_tags: { hook_style: 'contrarian', tone: 'authority', content_format: 'explainer', niche_signal: 'health', editing_style: 'whiteboard', audience_pain: 'health-anxiety' },
    thumbnail_color: '#004D40', views: 5_100_000, likes: 655_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'hlth-02',
    title: 'I tracked my sleep for 90 days. These 3 changes fixed everything',
    creator: '@sleeplab_chris',
    niche_tags: ['health', 'self-improvement'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'transformation', niche_signal: 'health', editing_style: 'b-roll-heavy', audience_pain: 'burnout' },
    thumbnail_color: '#00695C', views: 3_400_000, likes: 440_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'hlth-03',
    title: '5 symptoms you should never ignore (ER doctor explains)',
    creator: '@erdoc_priya',
    niche_tags: ['health', 'education'],
    attribute_tags: { hook_style: 'list_preview', tone: 'authority', content_format: 'listicle', niche_signal: 'health', editing_style: 'talking-head', audience_pain: 'health-anxiety' },
    thumbnail_color: '#00796B', views: 6_200_000, likes: 795_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'hlth-04',
    title: 'Cold plunge benefits: real science or just hype?',
    creator: '@evidencemed_dr',
    niche_tags: ['health', 'fitness'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'casual', content_format: 'comparison', niche_signal: 'health', editing_style: 'split-screen', audience_pain: 'information-overload' },
    thumbnail_color: '#00897B', views: 4_300_000, likes: 555_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'hlth-05',
    title: 'The gut health protocol that changed my life in 30 days',
    creator: '@gutfix_nina',
    niche_tags: ['health', 'food-nutrition'],
    attribute_tags: { hook_style: 'problem_identification', tone: 'motivational', content_format: 'story', niche_signal: 'health', editing_style: 'cinematic', audience_pain: 'health-anxiety' },
    thumbnail_color: '#009688', views: 5_700_000, likes: 730_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'hlth-06',
    title: 'Supplements ranked: what you actually need vs waste of money',
    creator: '@supplementscience',
    niche_tags: ['health', 'fitness'],
    attribute_tags: { hook_style: 'list_preview', tone: 'funny', content_format: 'review', niche_signal: 'health', editing_style: 'fast-cuts', audience_pain: 'money-anxiety' },
    thumbnail_color: '#26A69A', views: 3_600_000, likes: 465_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'hlth-07',
    title: 'Why walking is the most underrated exercise (doctor explains)',
    creator: '@walkmore_dr',
    niche_tags: ['health', 'fitness'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'health', editing_style: 'demo', audience_pain: 'time-scarcity' },
    thumbnail_color: '#4DB6AC', views: 2_800_000, likes: 360_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'hlth-08',
    title: 'The stress response hack therapists use on themselves',
    creator: '@stresshack_dr',
    niche_tags: ['health', 'psychology'],
    attribute_tags: { hook_style: 'authority', tone: 'authority', content_format: 'explainer', niche_signal: 'health', editing_style: 'vlog-style', audience_pain: 'burnout' },
    thumbnail_color: '#80CBC4', views: 4_100_000, likes: 530_000,
    performance_tier: 'average', placeholder: true,
  },

  // ── COOKING (8 videos) ───────────────────────────────────────────────────
  {
    id: 'cook-01',
    title: '15-minute meals that taste like you cooked all day',
    creator: '@quickchef_mia',
    niche_tags: ['cooking', 'food-nutrition'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'cooking', editing_style: 'demo', audience_pain: 'meal-fatigue' },
    thumbnail_color: '#E65100', views: 3_800_000, likes: 490_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'cook-02',
    title: 'Gordon Ramsay would hate this but it works every time',
    creator: '@lazycook_pete',
    niche_tags: ['cooking', 'food-nutrition'],
    attribute_tags: { hook_style: 'contrarian', tone: 'funny', content_format: 'story', niche_signal: 'cooking', editing_style: 'meme-edit', audience_pain: 'meal-fatigue' },
    thumbnail_color: '#BF360C', views: 5_500_000, likes: 710_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'cook-03',
    title: 'Meal prep Sunday: 5 lunches in 45 minutes for under $20',
    creator: '@preppro_dana',
    niche_tags: ['cooking', 'personal-finance'],
    attribute_tags: { hook_style: 'list_preview', tone: 'motivational', content_format: 'tutorial', niche_signal: 'cooking', editing_style: 'fast-cuts', audience_pain: 'time-scarcity' },
    thumbnail_color: '#D84315', views: 2_900_000, likes: 375_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'cook-04',
    title: 'I made every TikTok viral recipe. Only 3 are worth it',
    creator: '@viralrecipe_test',
    niche_tags: ['cooking', 'food-nutrition'],
    attribute_tags: { hook_style: 'question', tone: 'casual', content_format: 'review', niche_signal: 'cooking', editing_style: 'vlog-style', audience_pain: 'information-overload' },
    thumbnail_color: '#FF5722', views: 4_600_000, likes: 590_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'cook-05',
    title: 'The knife skill that makes you look like a pro chef',
    creator: '@chefskills_marco',
    niche_tags: ['cooking', 'education'],
    attribute_tags: { hook_style: 'authority', tone: 'authority', content_format: 'explainer', niche_signal: 'cooking', editing_style: 'cinematic', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#FF7043', views: 3_200_000, likes: 415_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'cook-06',
    title: 'One-pot pasta that feeds a family of 4 for $8',
    creator: '@budgetmeals_sam',
    niche_tags: ['cooking', 'personal-finance'],
    attribute_tags: { hook_style: 'personal_story', tone: 'casual', content_format: 'tutorial', niche_signal: 'cooking', editing_style: 'talking-head', audience_pain: 'money-anxiety' },
    thumbnail_color: '#FF8A65', views: 2_400_000, likes: 310_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'cook-07',
    title: '3 spice blends that will transform your cooking forever',
    creator: '@spicemaster_lu',
    niche_tags: ['cooking', 'food-nutrition'],
    attribute_tags: { hook_style: 'list_preview', tone: 'motivational', content_format: 'listicle', niche_signal: 'cooking', editing_style: 'before-after', audience_pain: 'meal-fatigue' },
    thumbnail_color: '#FFAB91', views: 4_800_000, likes: 615_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'cook-08',
    title: 'The mistakes ruining your steak (and how to fix them)',
    creator: '@grillscience_tom',
    niche_tags: ['cooking', 'food-nutrition'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'funny', content_format: 'comparison', niche_signal: 'cooking', editing_style: 'split-screen', audience_pain: 'information-overload' },
    thumbnail_color: '#FFCCBC', views: 5_900_000, likes: 760_000,
    performance_tier: 'high', placeholder: true,
  },

  // ── PSYCHOLOGY (8 videos) ────────────────────────────────────────────────
  {
    id: 'psy-01',
    title: 'The attachment style quiz everyone gets wrong',
    creator: '@mindlens_dr',
    niche_tags: ['psychology', 'dating'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'authority', content_format: 'explainer', niche_signal: 'psychology', editing_style: 'whiteboard', audience_pain: 'loneliness' },
    thumbnail_color: '#311B92', views: 4_200_000, likes: 540_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'psy-02',
    title: 'Why you self-sabotage (and how to stop today)',
    creator: '@therapytok_sam',
    niche_tags: ['psychology', 'self-improvement'],
    attribute_tags: { hook_style: 'authority', tone: 'motivational', content_format: 'explainer', niche_signal: 'psychology', editing_style: 'talking-head', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#4527A0', views: 3_600_000, likes: 465_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'psy-03',
    title: '3 signs you grew up with emotional neglect (most people miss #2)',
    creator: '@healingpath_dr',
    niche_tags: ['psychology', 'health'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'listicle', niche_signal: 'psychology', editing_style: 'b-roll-heavy', audience_pain: 'loneliness' },
    thumbnail_color: '#512DA8', views: 5_800_000, likes: 745_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'psy-04',
    title: 'The dopamine detox that actually works (neuroscientist explains)',
    creator: '@brainreset_dr',
    niche_tags: ['psychology', 'health'],
    attribute_tags: { hook_style: 'contrarian', tone: 'authority', content_format: 'tutorial', niche_signal: 'psychology', editing_style: 'fast-cuts', audience_pain: 'burnout' },
    thumbnail_color: '#5E35B1', views: 6_100_000, likes: 785_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'psy-05',
    title: 'How to read people instantly (FBI negotiator technique)',
    creator: '@readpeople_pro',
    niche_tags: ['psychology', 'career'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'story', niche_signal: 'psychology', editing_style: 'cinematic', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#673AB7', views: 4_400_000, likes: 565_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'psy-06',
    title: 'The gaslighting signs everyone ignores (therapist reacts)',
    creator: '@therapistreacts',
    niche_tags: ['psychology', 'dating'],
    attribute_tags: { hook_style: 'list_preview', tone: 'motivational', content_format: 'review', niche_signal: 'psychology', editing_style: 'demo', audience_pain: 'loneliness' },
    thumbnail_color: '#7E57C2', views: 5_200_000, likes: 670_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'psy-07',
    title: 'I tried CBT techniques for 30 days — honest results',
    creator: '@cbtchallenge_zoe',
    niche_tags: ['psychology', 'self-improvement'],
    attribute_tags: { hook_style: 'question', tone: 'funny', content_format: 'transformation', niche_signal: 'psychology', editing_style: 'vlog-style', audience_pain: 'burnout' },
    thumbnail_color: '#9575CD', views: 3_300_000, likes: 425_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'psy-08',
    title: 'Why your anxiety gets worse when you try to relax',
    creator: '@paradoxmind_dr',
    niche_tags: ['psychology', 'health'],
    attribute_tags: { hook_style: 'personal_story', tone: 'authority', content_format: 'comparison', niche_signal: 'psychology', editing_style: 'split-screen', audience_pain: 'health-anxiety' },
    thumbnail_color: '#B39DDB', views: 4_700_000, likes: 605_000,
    performance_tier: 'average', placeholder: true,
  },

  // ── TRAVEL (8 videos) ────────────────────────────────────────────────────
  {
    id: 'trav-01',
    title: 'How I travel full-time for less than my old rent',
    creator: '@nomadbudget_lee',
    niche_tags: ['travel', 'personal-finance'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'vlog', niche_signal: 'travel', editing_style: 'cinematic', audience_pain: 'wanderlust' },
    thumbnail_color: '#01579B', views: 4_400_000, likes: 565_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'trav-02',
    title: 'Tourist traps vs hidden gems: 5 cities compared',
    creator: '@realtravel_ana',
    niche_tags: ['travel', 'food-nutrition'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'comparison', niche_signal: 'travel', editing_style: 'fast-cuts', audience_pain: 'wanderlust' },
    thumbnail_color: '#0277BD', views: 3_700_000, likes: 475_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'trav-03',
    title: 'The packing hack flight attendants use (saves so much space)',
    creator: '@flylight_crew',
    niche_tags: ['travel', 'diy'],
    attribute_tags: { hook_style: 'authority', tone: 'funny', content_format: 'tutorial', niche_signal: 'travel', editing_style: 'demo', audience_pain: 'time-scarcity' },
    thumbnail_color: '#0288D1', views: 6_100_000, likes: 780_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'trav-04',
    title: 'Japan on $50/day — full budget breakdown',
    creator: '@budgetjapan_kai',
    niche_tags: ['travel', 'personal-finance'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'travel', editing_style: 'vlog-style', audience_pain: 'money-anxiety' },
    thumbnail_color: '#039BE5', views: 5_300_000, likes: 680_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'trav-05',
    title: 'I got a free business class upgrade using this trick',
    creator: '@hackthefly_sam',
    niche_tags: ['travel', 'side-hustles'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'story', niche_signal: 'travel', editing_style: 'talking-head', audience_pain: 'wanderlust' },
    thumbnail_color: '#03A9F4', views: 4_100_000, likes: 530_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'trav-06',
    title: 'Solo travel mistakes that could ruin your trip',
    creator: '@solotravel_nina',
    niche_tags: ['travel', 'self-improvement'],
    attribute_tags: { hook_style: 'list_preview', tone: 'authority', content_format: 'listicle', niche_signal: 'travel', editing_style: 'b-roll-heavy', audience_pain: 'information-overload' },
    thumbnail_color: '#29B6F6', views: 3_200_000, likes: 415_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'trav-07',
    title: 'The best street food in Southeast Asia ranked',
    creator: '@streetfood_world',
    niche_tags: ['travel', 'cooking'],
    attribute_tags: { hook_style: 'question', tone: 'funny', content_format: 'review', niche_signal: 'travel', editing_style: 'before-after', audience_pain: 'wanderlust' },
    thumbnail_color: '#4FC3F7', views: 5_800_000, likes: 745_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'trav-08',
    title: 'Digital nomad reality: the stuff Instagram doesn\'t show',
    creator: '@nomadtruth_dev',
    niche_tags: ['travel', 'career'],
    attribute_tags: { hook_style: 'contrarian', tone: 'casual', content_format: 'transformation', niche_signal: 'travel', editing_style: 'split-screen', audience_pain: 'burnout' },
    thumbnail_color: '#81D4FA', views: 4_600_000, likes: 590_000,
    performance_tier: 'average', placeholder: true,
  },

  // ── DIY (8 videos) ───────────────────────────────────────────────────────
  {
    id: 'diy-01',
    title: 'I renovated my bathroom for $200 (landlord approved)',
    creator: '@budgetreno_jake',
    niche_tags: ['diy', 'real-estate'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'transformation', niche_signal: 'diy', editing_style: 'before-after', audience_pain: 'home-frustration' },
    thumbnail_color: '#4E342E', views: 3_900_000, likes: 500_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'diy-02',
    title: '5 tool mistakes beginners always make (and easy fixes)',
    creator: '@workshopwiz_tom',
    niche_tags: ['diy', 'education'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'tutorial', niche_signal: 'diy', editing_style: 'demo', audience_pain: 'home-frustration' },
    thumbnail_color: '#5D4037', views: 2_600_000, likes: 335_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'diy-03',
    title: 'IKEA hack that looks like a $2000 custom built-in',
    creator: '@ikeahacks_lin',
    niche_tags: ['diy', 'fashion'],
    attribute_tags: { hook_style: 'question', tone: 'funny', content_format: 'comparison', niche_signal: 'diy', editing_style: 'cinematic', audience_pain: 'money-anxiety' },
    thumbnail_color: '#6D4C41', views: 5_300_000, likes: 680_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'diy-04',
    title: 'How to fix a running toilet in 5 minutes (save $200)',
    creator: '@fixitfast_amy',
    niche_tags: ['diy', 'personal-finance'],
    attribute_tags: { hook_style: 'authority', tone: 'casual', content_format: 'tutorial', niche_signal: 'diy', editing_style: 'talking-head', audience_pain: 'money-anxiety' },
    thumbnail_color: '#795548', views: 4_100_000, likes: 530_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'diy-05',
    title: 'The garage organization that changed my life',
    creator: '@organized_space',
    niche_tags: ['diy', 'self-improvement'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'transformation', niche_signal: 'diy', editing_style: 'before-after', audience_pain: 'home-frustration' },
    thumbnail_color: '#8D6E63', views: 3_400_000, likes: 440_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'diy-06',
    title: 'Paint colors that make small rooms feel twice as big',
    creator: '@paintpro_nina',
    niche_tags: ['diy', 'real-estate'],
    attribute_tags: { hook_style: 'list_preview', tone: 'authority', content_format: 'listicle', niche_signal: 'diy', editing_style: 'split-screen', audience_pain: 'home-frustration' },
    thumbnail_color: '#A1887F', views: 2_800_000, likes: 360_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'diy-07',
    title: 'Building a deck with zero experience (honest timeline)',
    creator: '@deckbuild_dan',
    niche_tags: ['diy', 'education'],
    attribute_tags: { hook_style: 'problem_identification', tone: 'casual', content_format: 'vlog', niche_signal: 'diy', editing_style: 'vlog-style', audience_pain: 'imposter-syndrome' },
    thumbnail_color: '#BCAAA4', views: 4_700_000, likes: 605_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'diy-08',
    title: 'Electrical basics every homeowner must know',
    creator: '@safewiring_pro',
    niche_tags: ['diy', 'education'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'authority', content_format: 'explainer', niche_signal: 'diy', editing_style: 'whiteboard', audience_pain: 'information-overload' },
    thumbnail_color: '#D7CCC8', views: 3_600_000, likes: 465_000,
    performance_tier: 'average', placeholder: true,
  },

  // ── LANGUAGE (8 videos) ──────────────────────────────────────────────────
  {
    id: 'lang-01',
    title: 'I became conversational in Spanish in 90 days using this method',
    creator: '@polyglot_kai',
    niche_tags: ['language', 'education'],
    attribute_tags: { hook_style: 'personal_story', tone: 'motivational', content_format: 'transformation', niche_signal: 'language', editing_style: 'vlog-style', audience_pain: 'language-barrier' },
    thumbnail_color: '#1A237E', views: 3_200_000, likes: 415_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'lang-02',
    title: 'Duolingo vs real immersion: which actually works?',
    creator: '@langtest_emma',
    niche_tags: ['language', 'tech'],
    attribute_tags: { hook_style: 'contrarian', tone: 'authority', content_format: 'comparison', niche_signal: 'language', editing_style: 'split-screen', audience_pain: 'language-barrier' },
    thumbnail_color: '#283593', views: 4_700_000, likes: 605_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'lang-03',
    title: '10 phrases that make you sound native in French',
    creator: '@frenchfluent_luc',
    niche_tags: ['language', 'travel'],
    attribute_tags: { hook_style: 'list_preview', tone: 'casual', content_format: 'listicle', niche_signal: 'language', editing_style: 'fast-cuts', audience_pain: 'language-barrier' },
    thumbnail_color: '#303F9F', views: 2_400_000, likes: 310_000,
    performance_tier: 'underperformer', placeholder: true,
  },
  {
    id: 'lang-04',
    title: 'The shadowing technique that polyglots swear by',
    creator: '@shadowmethod_dr',
    niche_tags: ['language', 'education'],
    attribute_tags: { hook_style: 'authority', tone: 'authority', content_format: 'tutorial', niche_signal: 'language', editing_style: 'demo', audience_pain: 'language-barrier' },
    thumbnail_color: '#3949AB', views: 3_800_000, likes: 490_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'lang-05',
    title: 'I spoke only Japanese for 7 days — embarrassing but effective',
    creator: '@immersiontest_jo',
    niche_tags: ['language', 'travel'],
    attribute_tags: { hook_style: 'question', tone: 'funny', content_format: 'vlog', niche_signal: 'language', editing_style: 'cinematic', audience_pain: 'language-barrier' },
    thumbnail_color: '#3F51B5', views: 5_400_000, likes: 695_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'lang-06',
    title: 'Why grammar-first learning is destroying your fluency',
    creator: '@fluencyfirst_al',
    niche_tags: ['language', 'education'],
    attribute_tags: { hook_style: 'myth_bust', tone: 'casual', content_format: 'explainer', niche_signal: 'language', editing_style: 'whiteboard', audience_pain: 'information-overload' },
    thumbnail_color: '#5C6BC0', views: 2_900_000, likes: 375_000,
    performance_tier: 'average', placeholder: true,
  },
  {
    id: 'lang-07',
    title: 'Best free resources to learn any language in 2026',
    creator: '@freelearn_dev',
    niche_tags: ['language', 'tech'],
    attribute_tags: { hook_style: 'list_preview', tone: 'motivational', content_format: 'listicle', niche_signal: 'language', editing_style: 'screen-record', audience_pain: 'money-anxiety' },
    thumbnail_color: '#7986CB', views: 4_100_000, likes: 530_000,
    performance_tier: 'high', placeholder: true,
  },
  {
    id: 'lang-08',
    title: 'How I maintained 4 languages without burning out',
    creator: '@langbalance_mia',
    niche_tags: ['language', 'self-improvement'],
    attribute_tags: { hook_style: 'personal_story', tone: 'casual', content_format: 'story', niche_signal: 'language', editing_style: 'talking-head', audience_pain: 'burnout' },
    thumbnail_color: '#9FA8DA', views: 1_800_000, likes: 235_000,
    performance_tier: 'underperformer', placeholder: true,
  },
];

// ─── Coverage Validation ─────────────────────────────────────────────────────
// Ensures every NICHE_REGISTRY niche has exactly 8 videos in the pool.

const nicheCounts = new Map<string, number>();
for (const v of VIDEO_POOL) {
  const ns = v.attribute_tags.niche_signal;
  nicheCounts.set(ns, (nicheCounts.get(ns) ?? 0) + 1);
}
const underNiches = NICHE_REGISTRY
  .filter((n) => (nicheCounts.get(n.key) ?? 0) < 8)
  .map((n) => `${n.key}(${nicheCounts.get(n.key) ?? 0})`);

if (underNiches.length > 0) {
  const msg = `[calibration-video-pool] Niches with <8 videos: ${underNiches.join(', ')}`;
  if (process.env.NODE_ENV === 'development') {
    throw new Error(msg);
  } else {
    console.warn(msg);
  }
}

// ─── Selection ───────────────────────────────────────────────────────────────

export function getCalibrationVideos(niche: string): CalibrationVideo[] {
  const normalizedNiche = niche.toLowerCase().trim();

  // Return ONLY videos matching this niche — no cross-niche mixing
  const nicheMatches = VIDEO_POOL.filter((v) =>
    v.attribute_tags.niche_signal === normalizedNiche
  );

  // Shuffle (Fisher-Yates) to avoid predictable ordering
  const result = [...nicheMatches];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }

  // Return up to 8
  return result.slice(0, 8);
}
