/**
 * Prompt 43 — Zod input schemas for all MCP tools.
 *
 * These drive the auto-generated documentation surfaced by the MCP
 * `tools/list` protocol call. Each schema has a top-level .describe()
 * so clients can render the tool purpose inline.
 *
 * Output shapes are NOT Zod-validated here (the MCP SDK doesn't
 * require it). Tool handlers return plain JSON that the SDK wraps
 * in text content blocks.
 */

import { z } from 'zod'

export const FetchClientKPIsInput = z
  .object({
    limit: z
      .number()
      .int()
      .min(1)
      .max(100)
      .default(20)
      .describe('Max clients to return. Capped at 100.'),
  })
  .describe(
    'Fetch aggregate KPIs for all clients (creators) in the authenticated agency. ' +
      'Returns creator count, total predictions, avg VPS score, last activity, and a per-client breakdown.',
  )

export const RunVPSPredictionInput = z
  .object({
    creator_id: z
      .string()
      .uuid()
      .describe(
        'UUID of the creator (must belong to the authenticated agency). Use FetchClientKPIs to discover creator ids.',
      ),
    limit: z
      .number()
      .int()
      .min(1)
      .max(20)
      .default(5)
      .describe('Max recent prediction runs to return.'),
  })
  .describe(
    'Fetch recent VPS (Viral Prediction Score) runs for one creator in the authenticated agency. ' +
      'Reads from the prediction_runs history. Live pipeline runs are NOT triggered through MCP — ' +
      'the pipeline takes 20+ seconds and would block interactive Claude sessions. ' +
      'Use the admin dashboard or /api/creator/predict to trigger new runs.',
  )

export const FetchTrendRadarInput = z
  .object({
    limit: z
      .number()
      .int()
      .min(1)
      .max(50)
      .default(10)
      .describe('Max cultural events to return.'),
    include_stale: z
      .boolean()
      .default(true)
      .describe(
        'Include events with velocity_score=0 (flagged stale: true in the response). ' +
          'Set false to exclude entirely.',
      ),
  })
  .describe(
    'Fetch the cultural-events trend radar, filtered to niches relevant to the authenticated agency. ' +
      'Events with velocity_score=0 are flagged stale=true so the caller can decide how to handle them.',
  )

export const FetchMorningBriefInput = z
  .object({
    date: z
      .string()
      .regex(/^\d{4}-\d{2}-\d{2}$/)
      .optional()
      .describe('ISO date YYYY-MM-DD. Defaults to most recent available brief.'),
  })
  .describe(
    'Fetch the most recent morning brief for the authenticated agency. Morning briefs are generated overnight by the autodream cron job.',
  )

export const GenerateContentBriefInput = z
  .object({
    client_id: z
      .string()
      .uuid()
      .optional()
      .describe(
        'Optional — restrict to briefs for one specific client (creator). Must belong to the authenticated agency.',
      ),
    limit: z
      .number()
      .int()
      .min(1)
      .max(20)
      .default(5)
      .describe('Max pre-generated briefs to return.'),
  })
  .describe(
    'Return the most recent pre-generated content briefs for the authenticated agency. ' +
      'Briefs are generated by a nightly pipeline — this tool reads from cache and does NOT kick off live generation. ' +
      'If no briefs exist yet, returns an empty list with a note.',
  )

// Used by the MCP server to register tools. Keep names in sync with handlers.
export const TOOL_REGISTRY = {
  FetchClientKPIs: FetchClientKPIsInput,
  RunVPSPrediction: RunVPSPredictionInput,
  FetchTrendRadar: FetchTrendRadarInput,
  FetchMorningBrief: FetchMorningBriefInput,
  GenerateContentBrief: GenerateContentBriefInput,
} as const

export type ToolName = keyof typeof TOOL_REGISTRY
