'use client'

import { useState, useCallback } from 'react'

// ═══════════════════════════════════════════════════════════════
// SHARED TYPES  (must stay in sync with FreedomOSTool.tsx)
// ═══════════════════════════════════════════════════════════════

type BusinessModelType = 'service' | 'digital_product' | 'content_affiliate'

interface ModelResult { type: BusinessModelType; name: string; description: string; score: number }
interface OfferResult { name: string; target: string; promise: string; deliverables: string[]; priceRange: string; firstVersionScope: string[] }
interface SprintDay { days: string; tasks: string[] }
interface RoadmapPhase { phase: string; weeks: string; milestones: string[]; kpis: string[] }
interface LeadsPlan { channel: string; dailyTarget: string; totalTarget: number; scripts: string[] }

interface Outputs {
  freedomNumber: number
  runwayMonths: number
  primary: ModelResult
  secondary: ModelResult
  rationale: string[]
  offer: OfferResult
  sprint: SprintDay[]
  roadmap: RoadmapPhase[]
  leads: LeadsPlan
}

interface Inputs {
  availableHours: number
  monthlyExpenses: number
  [key: string]: unknown
}

// ═══════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════

const cardStyle = { background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }

function SectionCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl p-5 sm:p-6 mb-4 print-section" style={cardStyle}>
      <h3 className="text-xs font-bold uppercase tracking-wider mb-4" style={{ color: 'rgba(255,255,255,0.4)' }}>{title}</h3>
      {children}
    </section>
  )
}

function formatSummary(outputs: Outputs): string {
  const lines = [
    'Financial Freedom OS — Your Plan',
    '================================',
    '',
    `Freedom Number: $${outputs.freedomNumber.toLocaleString()}/mo`,
    `Runway: ${outputs.runwayMonths} months`,
    '',
    `Recommended Model: ${outputs.primary.name}`,
    ...outputs.rationale.map(r => `  • ${r}`),
    '',
    `Starter Offer: ${outputs.offer.name}`,
    `  For: ${outputs.offer.target}`,
    `  Promise: ${outputs.offer.promise}`,
    `  Price: ${outputs.offer.priceRange}`,
    '',
    'First 7 Days:',
    ...outputs.sprint.slice(0, 3).flatMap(s => [`  ${s.days}:`, ...s.tasks.map(t => `    • ${t}`)]),
    '',
    '—',
    'Generated by Financial Freedom OS',
  ]
  return lines.join('\n')
}

// ═══════════════════════════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════════════════════════

export default function PlanResultsView({ outputs, planId }: { outputs: Outputs; inputs?: Inputs; planId: string }) {
  const [copied, setCopied] = useState<string | null>(null)

  const handleCopySummary = useCallback(async () => {
    const text = formatSummary(outputs)
    try { await navigator.clipboard.writeText(text) } catch {
      const ta = document.createElement('textarea')
      ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0'
      document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta)
    }
    setCopied('summary')
    console.log('[freedom-os/track] copy_summary', { planId })
    setTimeout(() => setCopied(null), 2000)
  }, [outputs, planId])

  const handleExportJSON = useCallback(() => {
    const blob = new Blob([JSON.stringify({ outputs, planId }, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `freedom-os-plan-${planId}.json`; a.click()
    URL.revokeObjectURL(url)
    console.log('[freedom-os/track] export_json', { planId })
  }, [outputs, planId])

  const handleSavePDF = useCallback(() => { window.print(); console.log('[freedom-os/track] export_pdf', { planId }) }, [planId])

  const handleCopyLink = useCallback(async () => {
    const url = typeof window !== 'undefined' ? window.location.href : ''
    try { await navigator.clipboard.writeText(url) } catch {}
    setCopied('link')
    console.log('[freedom-os/track] share_link', { planId })
    setTimeout(() => setCopied(null), 2000)
  }, [planId])

  return (
    <>
      {/* Summary bar */}
      <div
        className="rounded-xl px-5 py-4 mb-6 flex flex-col sm:flex-row sm:items-center gap-3"
        style={{ background: 'rgba(229,9,20,0.06)', border: '1px solid rgba(229,9,20,0.12)' }}
      >
        <div className="flex gap-6">
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.35)' }}>Freedom #</div>
            <div className="text-lg font-extrabold text-white">${outputs.freedomNumber.toLocaleString()}<span className="text-xs font-normal" style={{ color: 'rgba(255,255,255,0.4)' }}>/mo</span></div>
          </div>
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.35)' }}>Runway</div>
            <div className="text-lg font-extrabold text-white">{outputs.runwayMonths}<span className="text-xs font-normal" style={{ color: 'rgba(255,255,255,0.4)' }}> mo</span></div>
          </div>
        </div>
      </div>

      {/* A: Model Fit */}
      <SectionCard title="Business Model Fit">
        <div className="rounded-xl p-4 mb-3" style={{ background: 'rgba(229,9,20,0.06)', border: '1px solid rgba(229,9,20,0.12)' }}>
          <div className="text-xs font-bold uppercase tracking-wider mb-1" style={{ color: '#ff1744' }}>Recommended</div>
          <div className="text-base font-extrabold text-white mb-1">{outputs.primary.name}</div>
          <p className="text-xs" style={{ color: 'rgba(255,255,255,0.5)' }}>{outputs.primary.description}</p>
        </div>
        <div className="rounded-xl p-4 mb-4" style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="text-[10px] font-bold uppercase tracking-wider mb-1" style={{ color: 'rgba(255,255,255,0.3)' }}>Alternative</div>
          <div className="text-sm font-bold text-white mb-1">{outputs.secondary.name}</div>
          <p className="text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>{outputs.secondary.description}</p>
        </div>
        <div className="text-xs font-semibold mb-2" style={{ color: 'rgba(255,255,255,0.5)' }}>Why this model?</div>
        <ul className="space-y-1.5">
          {outputs.rationale.map((r, i) => (
            <li key={i} className="text-xs flex gap-2" style={{ color: 'rgba(255,255,255,0.6)' }}>
              <span style={{ color: '#ff1744' }}>&bull;</span>{r}
            </li>
          ))}
        </ul>
      </SectionCard>

      {/* B: Starter Offer */}
      <SectionCard title="Starter Offer Builder">
        <div className="space-y-3">
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Offer Name</div>
            <div className="text-base font-bold text-white">{outputs.offer.name}</div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Who It&apos;s For</div>
              <div className="text-xs" style={{ color: 'rgba(255,255,255,0.7)' }}>{outputs.offer.target}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Promise</div>
              <div className="text-xs" style={{ color: 'rgba(255,255,255,0.7)' }}>{outputs.offer.promise}</div>
            </div>
          </div>
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: 'rgba(255,255,255,0.3)' }}>Deliverables</div>
            <ul className="space-y-1">
              {outputs.offer.deliverables.map((d, i) => (
                <li key={i} className="text-xs flex gap-2" style={{ color: 'rgba(255,255,255,0.65)' }}>
                  <span style={{ color: '#ff1744' }}>{i + 1}.</span>{d}
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-lg px-4 py-3 flex items-center justify-between" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}>
            <span className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Suggested Price</span>
            <span className="text-sm font-extrabold text-white">{outputs.offer.priceRange}</span>
          </div>
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: 'rgba(255,255,255,0.3)' }}>First Version Scope Rules</div>
            <ul className="space-y-1">
              {outputs.offer.firstVersionScope.map((s, i) => (
                <li key={i} className="text-xs flex gap-2" style={{ color: 'rgba(255,255,255,0.5)' }}>
                  <span>&#10003;</span>{s}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </SectionCard>

      {/* C: 14-Day Sprint */}
      <SectionCard title="14-Day Launch Sprint">
        <div className="space-y-4">
          {outputs.sprint.map((block, i) => (
            <div key={i}>
              <div className="text-xs font-bold text-white mb-2">{block.days}</div>
              <ul className="space-y-1.5">
                {block.tasks.map((t, j) => (
                  <li key={j} className="text-xs flex gap-2" style={{ color: 'rgba(255,255,255,0.6)' }}>
                    <span className="shrink-0 w-4 h-4 rounded border flex items-center justify-center text-[10px]" style={{ borderColor: 'rgba(255,255,255,0.12)' }}>&nbsp;</span>
                    {t}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* D: 90-Day Roadmap */}
      <SectionCard title="90-Day Scale Roadmap">
        <div className="space-y-5">
          {outputs.roadmap.map((phase, i) => (
            <div key={i} className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)' }}>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-bold text-white">{phase.phase}</span>
                <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full" style={{ background: 'rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.4)' }}>{phase.weeks}</span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <div className="text-[10px] font-bold uppercase tracking-wider mb-1.5" style={{ color: 'rgba(255,255,255,0.3)' }}>Milestones</div>
                  <ul className="space-y-1">
                    {phase.milestones.map((m, j) => (
                      <li key={j} className="text-xs" style={{ color: 'rgba(255,255,255,0.6)' }}>&bull; {m}</li>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="text-[10px] font-bold uppercase tracking-wider mb-1.5" style={{ color: 'rgba(255,255,255,0.3)' }}>KPIs</div>
                  <ul className="space-y-1">
                    {phase.kpis.map((k, j) => (
                      <li key={j} className="text-xs" style={{ color: 'rgba(255,255,255,0.5)' }}>{k}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* E: First 50 Leads */}
      <SectionCard title="First 50 Leads Plan">
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Channel</div>
              <div className="text-sm font-bold text-white">{outputs.leads.channel}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.3)' }}>Daily Target</div>
              <div className="text-sm font-bold text-white">{outputs.leads.dailyTarget}</div>
            </div>
          </div>
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: 'rgba(255,255,255,0.3)' }}>Script Templates</div>
            <div className="space-y-2">
              {outputs.leads.scripts.map((script, i) => (
                <div key={i} className="rounded-lg px-4 py-3 text-xs italic leading-relaxed" style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.6)' }}>
                  {script}
                </div>
              ))}
            </div>
          </div>
        </div>
      </SectionCard>

      {/* Export actions */}
      <div className="print-hide rounded-2xl p-4 sm:p-5 mb-4 flex flex-wrap items-center gap-2" style={cardStyle}>
        <button onClick={handleSavePDF}
          className="px-4 py-2.5 rounded-xl text-xs font-bold transition-all flex items-center gap-2"
          style={{ background: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.6)', border: '1px solid rgba(255,255,255,0.08)' }}>
          Save as PDF
        </button>
        <button onClick={handleCopySummary}
          className="px-4 py-2.5 rounded-xl text-xs font-bold transition-all flex items-center gap-2"
          style={{ background: copied === 'summary' ? 'rgba(16,185,129,0.12)' : 'rgba(255,255,255,0.05)', color: copied === 'summary' ? '#10b981' : 'rgba(255,255,255,0.6)', border: `1px solid ${copied === 'summary' ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.08)'}` }}>
          {copied === 'summary' ? 'Copied!' : 'Copy Summary'}
        </button>
        <button onClick={handleExportJSON}
          className="px-4 py-2.5 rounded-xl text-xs font-bold transition-all flex items-center gap-2"
          style={{ background: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.6)', border: '1px solid rgba(255,255,255,0.08)' }}>
          Export JSON
        </button>
        <button onClick={handleCopyLink}
          className="px-4 py-2.5 rounded-xl text-xs font-bold transition-all flex items-center gap-2 ml-auto"
          style={{ background: copied === 'link' ? 'rgba(16,185,129,0.12)' : 'rgba(255,255,255,0.04)', color: copied === 'link' ? '#10b981' : 'rgba(255,255,255,0.4)', border: `1px solid ${copied === 'link' ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.06)'}` }}>
          {copied === 'link' ? 'Copied!' : 'Share Link'}
        </button>
      </div>
    </>
  )
}
