name: CI

on:
  push:
    branches: [ main, develop ] # Or your primary development branches
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # —Å—Ç—Ä–∞—Ç–µ–≥–∏—è –¥–ª—è –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω–æ–≥–æ –∑–∞–ø—É—Å–∫–∞ —Ç–µ—Å—Ç–æ–≤ –µ—Å–ª–∏ –ø–æ—Ç—Ä–µ–±—É–µ—Ç—Å—è –≤ –±—É–¥—É—â–µ–º
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x] # –ü—Ä–∏–º–µ—Ä –≤–µ—Ä—Å–∏–π Node.js

    env:
      # –í–∞–∂–Ω–æ: –£—Å—Ç–∞–Ω–æ–≤–∏—Ç–µ —ç—Ç–∏ —Å–µ–∫—Ä–µ—Ç—ã –≤ –Ω–∞—Å—Ç—Ä–æ–π–∫–∞—Ö –≤–∞—à–µ–≥–æ GitHub —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è
      # Settings > Secrets and variables > Actions > New repository secret
      # NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} # –ó–∞–∫–æ–º–º–µ–Ω—Ç–∏—Ä–æ–≤–∞–Ω–æ, —Ç.–∫. Firebase —É–¥–∞–ª—è–µ—Ç—Å—è
      # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      # NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      # NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # –î–ª—è —Ç–µ—Å—Ç–æ–≤ Playwright, –∫–æ—Ç–æ—Ä—ã–µ –º–æ–≥—É—Ç –≤—ã–ø–æ–ª–Ω—è—Ç—å –¥–µ–π—Å—Ç–≤–∏—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–∞ –∏–ª–∏ —Ç—Ä–µ–±–æ–≤–∞—Ç—å —Å–µ—Ä–≤–∏—Å–Ω—ã–π –∫–ª—é—á:
      # SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} 
      
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # –ï—Å–ª–∏ –±—É–¥–µ—Ç–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å AI triage

      # –ü–µ—Ä–µ–º–µ–Ω–Ω—ã–µ –æ–∫—Ä—É–∂–µ–Ω–∏—è –¥–ª—è CI
      CI: true

    steps:
      - name: üõéÔ∏è Checkout repository
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup Node.js and pnpm
        uses: pnpm/action-setup@v3 # –û–±–Ω–æ–≤–ª–µ–Ω–æ –¥–æ v3
        with:
          version: 8 # –£–∫–∞–∂–∏—Ç–µ –≤–∞—à—É –≤–µ—Ä—Å–∏—é pnpm, –µ—Å–ª–∏ –æ—Ç–ª–∏—á–∞–µ—Ç—Å—è
      - name: Use Node.js ${{ matrix.node-version || '20.x' }} # –ò—Å–ø–æ–ª—å–∑—É–π—Ç–µ matrix –∏–ª–∏ –≤–µ—Ä—Å–∏—é –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version || '20.x' }}
          cache: 'pnpm'

      - name: üì¶ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: üé® Lint code
        run: pnpm run lint # –£–±–µ–¥–∏—Ç–µ—Å—å, —á—Ç–æ —É –≤–∞—Å –µ—Å—Ç—å —Å–∫—Ä–∏–ø—Ç "lint" –≤ package.json

      - name:  ¶ Type check
        run: pnpm run typecheck # –£–±–µ–¥–∏—Ç–µ—Å—å, —á—Ç–æ —É –≤–∞—Å –µ—Å—Ç—å —Å–∫—Ä–∏–ø—Ç "typecheck" –≤ package.json (–æ–±—ã—á–Ω–æ tsc --noEmit)
      
      - name: üèóÔ∏è Build project
        run: pnpm run build # –£–±–µ–¥–∏—Ç–µ—Å—å, —á—Ç–æ —É –≤–∞—Å –µ—Å—Ç—å —Å–∫—Ä–∏–ø—Ç "build" –≤ package.json

      # –£—Å—Ç–∞–Ω–æ–≤–∫–∞ Playwright Browsers –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å –¥–æ –∑–∞–ø—É—Å–∫–∞ —Ç–µ—Å—Ç–æ–≤
      - name:  playwright browsers
        run: pnpm exec playwright install --with-deps
      
      - name: üß™ Run Playwright E2E tests
        id: e2e_tests # –¥–∞–¥–∏–º id –¥–ª—è —à–∞–≥–∞ —á—Ç–æ–±—ã –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –µ–≥–æ –≤—ã–≤–æ–¥
        # –ó–∞–ø—É—Å–∫–∞–µ–º —Ç–µ—Å—Ç—ã –∏ –ø—Ä–æ–¥–æ–ª–∂–∞–µ–º –¥–∞–∂–µ –µ—Å–ª–∏ –æ–Ω–∏ —É–ø–∞–¥—É—Ç, —á—Ç–æ–±—ã –æ–±—Ä–∞–±–æ—Ç–∞—Ç—å –æ—à–∏–±–∫—É
        run: pnpm exec playwright test || echo "::set-output name=PLAYWRIGHT_TESTS_FAILED::true" 
        # –ï—Å–ª–∏ –≤—ã —Ö–æ—Ç–∏—Ç–µ —á—Ç–æ–±—ã CI –ø–∞–¥–∞–ª –ø—Ä–∏ –æ—à–∏–±–∫–∞—Ö —Ç–µ—Å—Ç–æ–≤ playwright test

      # –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π —à–∞–≥: AI Triage (–µ—Å–ª–∏ —Ç–µ—Å—Ç—ã —É–ø–∞–ª–∏)
      # - name: ü§ñ AI Triage & PR for failed tests
      #   if: steps.e2e_tests.outputs.PLAYWRIGHT_TESTS_FAILED == 'true'
      #   run: |
      #     echo "Playwright tests failed. Initiating AI Triage..."
      #     # node src/utils/aiTriage.ts # –ü—Ä–µ–¥–ø–æ–ª–∞–≥–∞—è —á—Ç–æ —É –≤–∞—Å –µ—Å—Ç—å —Ç–∞–∫–æ–π —Å–∫—Ä–∏–ø—Ç
      #     # –≠—Ç–æ—Ç —Å–∫—Ä–∏–ø—Ç –¥–æ–ª–∂–µ–Ω –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å OPENAI_API_KEY
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # –î–ª—è —Å–æ–∑–¥–∞–Ω–∏—è PR

      # –ü—Ä–∏–º–µ—Ä –∑–∞–≥—Ä—É–∑–∫–∏ –∞—Ä—Ç–µ—Ñ–∞–∫—Ç–æ–≤ —Å–±–æ—Ä–∫–∏ (–µ—Å–ª–∏ –Ω—É–∂–Ω–æ)
      # - name: üì§ Upload build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: production-build
      #     path: .next/ # –∏–ª–∏ –≤–∞—à–∞ –ø–∞–ø–∫–∞ —Å–±–æ—Ä–∫–∏

      # –ü—Ä–∏–º–µ—Ä –∑–∞–≥—Ä—É–∑–∫–∏ –æ—Ç—á–µ—Ç–æ–≤ Playwright (–≤—Å–µ–≥–¥–∞, –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞)
      - name: üì§ Upload Playwright Test Report
        if: always() # –ó–∞–≥—Ä—É–∂–∞–µ–º –æ—Ç—á–µ—Ç –≤—Å–µ–≥–¥–∞, –¥–∞–∂–µ –µ—Å–ª–∏ —Ç–µ—Å—Ç—ã –ø—Ä–æ—à–ª–∏ —É—Å–ø–µ—à–Ω–æ –∏–ª–∏ —É–ø–∞–ª–∏
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7 # –•—Ä–∞–Ω–∏—Ç—å –æ—Ç—á–µ—Ç—ã 7 –¥–Ω–µ–π

      # –ï—Å–ª–∏ —Ç–µ—Å—Ç—ã Playwright —É–ø–∞–ª–∏ –∏ –≤—ã —Ö–æ—Ç–∏—Ç–µ —á—Ç–æ–±—ã CI –∑–∞–≤–µ—Ä—à–∏–ª—Å—è —Å –æ—à–∏–±–∫–æ–π:
      - name: Check Playwright test results
        if: steps.e2e_tests.outputs.PLAYWRIGHT_TESTS_FAILED == 'true'
        run: |
          echo "Playwright tests failed. See uploaded report for details."
          exit 1
